services:
  - type: web
    name: bagisto-app
    env: php
    plan: free
    buildCommand: |
      composer install --no-dev
      npm install
      npm run prod
      php artisan migrate --force
      php artisan db:seed --force
    startCommand: php artisan serve --host 0.0.0.0 --port 10000
    rootDir: .
